version: "3"
services:
  backend:
    build: ./backend/
    container_name: asp-backend
    ports:
      - "9999:5000"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /root/.docker/config.json:/config.json
    #command: watchtower asp-backend --schedule '0 0 0 * * *' --cleanup --debug # spezifische container automatisch updaten
    environment:
      TZ: Europe/Brussels
      WATCHTOWER_SCHEDULE: 0 */1 * ? * *
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    restart: always